### ISSUE TITLE
Missing unit test for Python API

### ISSUE THREAD

**Issue by duburcqa** [Wandercraft/jiminy#39]
It would be cautious to have a basic unit test in Python checking that the Python API is working properly. The idea is just to check that it is possible to run a simulation without segfault, which may happen in practice if Eigenpy and Boost Python are not properly initialized.

**Comment by matthieuvigne** [comment]
Agreed - but since we are running a simulation,  it would be nice to check the results as well :) My idea is to simulate simple linear systems with Jiminy, and make sure that the solution matches the expected analytical answer. This provides a high-level sanity check for Jiminy, that would complement the only unit test we have (which simply tests for energy conservation is a pendulum, but doesn't look at the actual answer)

**Comment by duburcqa** [comment]
By the way, "duplicate" the examples in unit tests may be a good idea.

**Comment by duburcqa** [comment]
@matthieuvigne Do you think we are good and that we can close this issue ?
